/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WatchusdctransferLazyImport = createFileRoute('/watch_usdc_transfer')()
const WatchblocksLazyImport = createFileRoute('/watch_blocks')()
const TransferusdcLazyImport = createFileRoute('/transfer_usdc')()
const SignmessageLazyImport = createFileRoute('/sign_message')()
const SendethwithfillersLazyImport = createFileRoute('/send_eth_with_fillers')()
const SendethLazyImport = createFileRoute('/send_eth')()
const GetlatestblockLazyImport = createFileRoute('/get_latest_block')()
const GetbatchbalancesLazyImport = createFileRoute('/get_batch_balances')()
const GetbalanceusdcLazyImport = createFileRoute('/get_balance_usdc')()
const GetbalanceLazyImport = createFileRoute('/get_balance')()
const GetaddressLazyImport = createFileRoute('/get_address')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WatchusdctransferLazyRoute = WatchusdctransferLazyImport.update({
  path: '/watch_usdc_transfer',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/watch_usdc_transfer.lazy').then((d) => d.Route),
)

const WatchblocksLazyRoute = WatchblocksLazyImport.update({
  path: '/watch_blocks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/watch_blocks.lazy').then((d) => d.Route))

const TransferusdcLazyRoute = TransferusdcLazyImport.update({
  path: '/transfer_usdc',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/transfer_usdc.lazy').then((d) => d.Route))

const SignmessageLazyRoute = SignmessageLazyImport.update({
  path: '/sign_message',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign_message.lazy').then((d) => d.Route))

const SendethwithfillersLazyRoute = SendethwithfillersLazyImport.update({
  path: '/send_eth_with_fillers',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/send_eth_with_fillers.lazy').then((d) => d.Route),
)

const SendethLazyRoute = SendethLazyImport.update({
  path: '/send_eth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/send_eth.lazy').then((d) => d.Route))

const GetlatestblockLazyRoute = GetlatestblockLazyImport.update({
  path: '/get_latest_block',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/get_latest_block.lazy').then((d) => d.Route),
)

const GetbatchbalancesLazyRoute = GetbatchbalancesLazyImport.update({
  path: '/get_batch_balances',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/get_batch_balances.lazy').then((d) => d.Route),
)

const GetbalanceusdcLazyRoute = GetbalanceusdcLazyImport.update({
  path: '/get_balance_usdc',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/get_balance_usdc.lazy').then((d) => d.Route),
)

const GetbalanceLazyRoute = GetbalanceLazyImport.update({
  path: '/get_balance',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/get_balance.lazy').then((d) => d.Route))

const GetaddressLazyRoute = GetaddressLazyImport.update({
  path: '/get_address',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/get_address.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/get_address': {
      id: '/get_address'
      path: '/get_address'
      fullPath: '/get_address'
      preLoaderRoute: typeof GetaddressLazyImport
      parentRoute: typeof rootRoute
    }
    '/get_balance': {
      id: '/get_balance'
      path: '/get_balance'
      fullPath: '/get_balance'
      preLoaderRoute: typeof GetbalanceLazyImport
      parentRoute: typeof rootRoute
    }
    '/get_balance_usdc': {
      id: '/get_balance_usdc'
      path: '/get_balance_usdc'
      fullPath: '/get_balance_usdc'
      preLoaderRoute: typeof GetbalanceusdcLazyImport
      parentRoute: typeof rootRoute
    }
    '/get_batch_balances': {
      id: '/get_batch_balances'
      path: '/get_batch_balances'
      fullPath: '/get_batch_balances'
      preLoaderRoute: typeof GetbatchbalancesLazyImport
      parentRoute: typeof rootRoute
    }
    '/get_latest_block': {
      id: '/get_latest_block'
      path: '/get_latest_block'
      fullPath: '/get_latest_block'
      preLoaderRoute: typeof GetlatestblockLazyImport
      parentRoute: typeof rootRoute
    }
    '/send_eth': {
      id: '/send_eth'
      path: '/send_eth'
      fullPath: '/send_eth'
      preLoaderRoute: typeof SendethLazyImport
      parentRoute: typeof rootRoute
    }
    '/send_eth_with_fillers': {
      id: '/send_eth_with_fillers'
      path: '/send_eth_with_fillers'
      fullPath: '/send_eth_with_fillers'
      preLoaderRoute: typeof SendethwithfillersLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign_message': {
      id: '/sign_message'
      path: '/sign_message'
      fullPath: '/sign_message'
      preLoaderRoute: typeof SignmessageLazyImport
      parentRoute: typeof rootRoute
    }
    '/transfer_usdc': {
      id: '/transfer_usdc'
      path: '/transfer_usdc'
      fullPath: '/transfer_usdc'
      preLoaderRoute: typeof TransferusdcLazyImport
      parentRoute: typeof rootRoute
    }
    '/watch_blocks': {
      id: '/watch_blocks'
      path: '/watch_blocks'
      fullPath: '/watch_blocks'
      preLoaderRoute: typeof WatchblocksLazyImport
      parentRoute: typeof rootRoute
    }
    '/watch_usdc_transfer': {
      id: '/watch_usdc_transfer'
      path: '/watch_usdc_transfer'
      fullPath: '/watch_usdc_transfer'
      preLoaderRoute: typeof WatchusdctransferLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/get_address': typeof GetaddressLazyRoute
  '/get_balance': typeof GetbalanceLazyRoute
  '/get_balance_usdc': typeof GetbalanceusdcLazyRoute
  '/get_batch_balances': typeof GetbatchbalancesLazyRoute
  '/get_latest_block': typeof GetlatestblockLazyRoute
  '/send_eth': typeof SendethLazyRoute
  '/send_eth_with_fillers': typeof SendethwithfillersLazyRoute
  '/sign_message': typeof SignmessageLazyRoute
  '/transfer_usdc': typeof TransferusdcLazyRoute
  '/watch_blocks': typeof WatchblocksLazyRoute
  '/watch_usdc_transfer': typeof WatchusdctransferLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/get_address': typeof GetaddressLazyRoute
  '/get_balance': typeof GetbalanceLazyRoute
  '/get_balance_usdc': typeof GetbalanceusdcLazyRoute
  '/get_batch_balances': typeof GetbatchbalancesLazyRoute
  '/get_latest_block': typeof GetlatestblockLazyRoute
  '/send_eth': typeof SendethLazyRoute
  '/send_eth_with_fillers': typeof SendethwithfillersLazyRoute
  '/sign_message': typeof SignmessageLazyRoute
  '/transfer_usdc': typeof TransferusdcLazyRoute
  '/watch_blocks': typeof WatchblocksLazyRoute
  '/watch_usdc_transfer': typeof WatchusdctransferLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/get_address': typeof GetaddressLazyRoute
  '/get_balance': typeof GetbalanceLazyRoute
  '/get_balance_usdc': typeof GetbalanceusdcLazyRoute
  '/get_batch_balances': typeof GetbatchbalancesLazyRoute
  '/get_latest_block': typeof GetlatestblockLazyRoute
  '/send_eth': typeof SendethLazyRoute
  '/send_eth_with_fillers': typeof SendethwithfillersLazyRoute
  '/sign_message': typeof SignmessageLazyRoute
  '/transfer_usdc': typeof TransferusdcLazyRoute
  '/watch_blocks': typeof WatchblocksLazyRoute
  '/watch_usdc_transfer': typeof WatchusdctransferLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get_address'
    | '/get_balance'
    | '/get_balance_usdc'
    | '/get_batch_balances'
    | '/get_latest_block'
    | '/send_eth'
    | '/send_eth_with_fillers'
    | '/sign_message'
    | '/transfer_usdc'
    | '/watch_blocks'
    | '/watch_usdc_transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get_address'
    | '/get_balance'
    | '/get_balance_usdc'
    | '/get_batch_balances'
    | '/get_latest_block'
    | '/send_eth'
    | '/send_eth_with_fillers'
    | '/sign_message'
    | '/transfer_usdc'
    | '/watch_blocks'
    | '/watch_usdc_transfer'
  id:
    | '__root__'
    | '/'
    | '/get_address'
    | '/get_balance'
    | '/get_balance_usdc'
    | '/get_batch_balances'
    | '/get_latest_block'
    | '/send_eth'
    | '/send_eth_with_fillers'
    | '/sign_message'
    | '/transfer_usdc'
    | '/watch_blocks'
    | '/watch_usdc_transfer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GetaddressLazyRoute: typeof GetaddressLazyRoute
  GetbalanceLazyRoute: typeof GetbalanceLazyRoute
  GetbalanceusdcLazyRoute: typeof GetbalanceusdcLazyRoute
  GetbatchbalancesLazyRoute: typeof GetbatchbalancesLazyRoute
  GetlatestblockLazyRoute: typeof GetlatestblockLazyRoute
  SendethLazyRoute: typeof SendethLazyRoute
  SendethwithfillersLazyRoute: typeof SendethwithfillersLazyRoute
  SignmessageLazyRoute: typeof SignmessageLazyRoute
  TransferusdcLazyRoute: typeof TransferusdcLazyRoute
  WatchblocksLazyRoute: typeof WatchblocksLazyRoute
  WatchusdctransferLazyRoute: typeof WatchusdctransferLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GetaddressLazyRoute: GetaddressLazyRoute,
  GetbalanceLazyRoute: GetbalanceLazyRoute,
  GetbalanceusdcLazyRoute: GetbalanceusdcLazyRoute,
  GetbatchbalancesLazyRoute: GetbatchbalancesLazyRoute,
  GetlatestblockLazyRoute: GetlatestblockLazyRoute,
  SendethLazyRoute: SendethLazyRoute,
  SendethwithfillersLazyRoute: SendethwithfillersLazyRoute,
  SignmessageLazyRoute: SignmessageLazyRoute,
  TransferusdcLazyRoute: TransferusdcLazyRoute,
  WatchblocksLazyRoute: WatchblocksLazyRoute,
  WatchusdctransferLazyRoute: WatchusdctransferLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/get_address",
        "/get_balance",
        "/get_balance_usdc",
        "/get_batch_balances",
        "/get_latest_block",
        "/send_eth",
        "/send_eth_with_fillers",
        "/sign_message",
        "/transfer_usdc",
        "/watch_blocks",
        "/watch_usdc_transfer"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/get_address": {
      "filePath": "get_address.lazy.tsx"
    },
    "/get_balance": {
      "filePath": "get_balance.lazy.tsx"
    },
    "/get_balance_usdc": {
      "filePath": "get_balance_usdc.lazy.tsx"
    },
    "/get_batch_balances": {
      "filePath": "get_batch_balances.lazy.tsx"
    },
    "/get_latest_block": {
      "filePath": "get_latest_block.lazy.tsx"
    },
    "/send_eth": {
      "filePath": "send_eth.lazy.tsx"
    },
    "/send_eth_with_fillers": {
      "filePath": "send_eth_with_fillers.lazy.tsx"
    },
    "/sign_message": {
      "filePath": "sign_message.lazy.tsx"
    },
    "/transfer_usdc": {
      "filePath": "transfer_usdc.lazy.tsx"
    },
    "/watch_blocks": {
      "filePath": "watch_blocks.lazy.tsx"
    },
    "/watch_usdc_transfer": {
      "filePath": "watch_usdc_transfer.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
